// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int above0_5 = 0;
	    int below0_5 = 0;
		
		for (int i = 0; i < Integer.parseInt(args[0]); i++) {
			double randValue = Math.random();
			if (randValue < 0.5) {
				below0_5++;
			} else {
				above0_5++;
			}
		}
		System.out.println(String.format("> 0.5: %s times", above0_5));
		System.out.println(String.format("<= 0.5: %s times", below0_5));
		if (above0_5 != 0 && below0_5 != 0) {
			System.out.println(String.format("Ratio: %s", (double) below0_5 / above0_5));		
		}
	}
}
